/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class smartcardemuhost_pcsc_PcScClass */

#ifndef _Included_smartcardemuhost_pcsc_PcScClass
#define _Included_smartcardemuhost_pcsc_PcScClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     smartcardemuhost_pcsc_PcScClass
 * Method:    getReaderList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_smartcardemuhost_pcsc_PcScClass_getReaderList
  (JNIEnv *, jclass);

/*
 * Class:     smartcardemuhost_pcsc_PcScClass
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_smartcardemuhost_pcsc_PcScClass_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     smartcardemuhost_pcsc_PcScClass
 * Method:    resetCard
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_smartcardemuhost_pcsc_PcScClass_resetCard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     smartcardemuhost_pcsc_PcScClass
 * Method:    closeCard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_smartcardemuhost_pcsc_PcScClass_closeCard
  (JNIEnv *, jclass);

/*
 * Class:     smartcardemuhost_pcsc_PcScClass
 * Method:    sendCmd
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_smartcardemuhost_pcsc_PcScClass_sendCmd
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
